name: Deploy Backend

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master
    paths:
      - "Pallas.API/**"
      - ".github/workflows/backend.yml"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: Pallas.API
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/pallas-api:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }} 
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/pallas-api:latest
            docker stop pallas-api || true
            docker rm pallas-api || true
            docker run -d --name pallas-api -p 5000:5000 ghcr.io/${{ github.repository_owner }}/pallas-api:latest
